### ISSUE TITLE
CSS grid + flexbox layout

### ISSUE THREAD

**Issue by idsintehittapa** [idsintehittapa/my-miscarriage#3]
Organise page with grid and flexbox

**Comment by carlacentenor** [comment]
Hello 
I would like to work on it. :)

**Comment by idsintehittapa** [comment]
@carlacentenor go for it! :)

**Comment by idsintehittapa** [comment]
@RamanaVem, @carlacentenor is already working on this

**Comment by idsintehittapa** [comment]
Flex implemented
